name 'chef_task_2'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures chef_task_2'
long_description 'Installs/Configures chef_task_2'
version '0.1.0'
issues_url 'https://github.com/DZUBA/chef_test_2'
source_url 'https://github.com/DZUBA/chef_test_2'

depends 'yum', '~> 4.1.0'
